# Generated by Django 5.1.7 on 2025-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_img_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
