# Generated by Django 5.1.7 on 2025-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='order',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='takeoutitem',
            old_name='order',
            new_name='takeout',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
