# Generated by Django 5.1.7 on 2025-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delivery_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='assigned_to',
        ),
    ]
