# Generated by Django 5.1.7 on 2025-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_delivery_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutish jarayonida'), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivering', 'Yetkazilmoqda'), ('served', 'Yetkazildi')], default='pending', max_length=20),
        ),
    ]
